apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-check
  namespace: network-check
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-check
subjects:
- kind: ServiceAccount
  name: network-check
  namespace: network-check
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-check
  namespace: network-check
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  - routes/status
  verbs:
  - get
  - list
  - watch
